### PR TITLE
Add Source Han Mono

### PR DESCRIPTION
**Pull request by extratype**
It worked for Source Han Mono 1.002.

### CODE REVIEW

**Comment by m13253** [comment]
Thank you for the update.
Since building these fonts requires around 24-32 GiB of RAM and at the moment I don't own such a machine.
Can you build the latest version for us? (using the latest files from Adobe)

**Comment by m13253** [comment]
By the way, I fixed a font name in commit 3b9ab47e01a97076214e3e465dd0692314f2d34d.

**Comment by extratype** [comment]
https://drive.google.com/drive/folders/1KU8KOThk4GE8zqUWaUYFenWvFZjJYhxW?usp=sharing

Fonts built using https://github.com/m13253/kaigen-fonts/pull/2/commits/a345c23a5dfdba7e20f9e4e0c176fbd132991c0d.

* Source Han Sans 2.002
* Source Han Serif 1.001
* Source Han Mono 1.002

**Comment by extratype** [comment]
Copyright was not appended in Source Han Sans and Source Han Mono. The original copyright had been changed a bit.

**Comment by m13253** [comment]
> Copyright was not appended in Source Han Sans and Source Han Mono. The original copyright had been changed a bit.

Oh I found it. The new copyright text removed the word “Copyright” so the RegExp can no longer match that string. 😅

I will just leave it as is for a moment and fix them later (when I have access to powerful machines to build the fonts, probably after the pandemic is over.)

**Comment by m13253** [comment]
> https://drive.google.com/drive/folders/1KU8KOThk4GE8zqUWaUYFenWvFZjJYhxW?usp=sharing

Thank you! I uploaded to https://github.com/m13253/kaigen-fonts/releases/tag/v2.002-1.001-1.002-1 .

**Pull request merged**
